// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_PM0YNPFIZcFxG0LXyLSofyOib8gMrNs',
    appId: '1:350364495319:web:11dbd687d59c8a4c8aaf92',
    messagingSenderId: '350364495319',
    projectId: 'say-to-muavia',
    authDomain: 'say-to-muavia.firebaseapp.com',
    storageBucket: 'say-to-muavia.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxk7vILaAw_Nvh4oq4OrJMVZ5WvxmaYjA',
    appId: '1:350364495319:android:221c285e2c7f04948aaf92',
    messagingSenderId: '350364495319',
    projectId: 'say-to-muavia',
    storageBucket: 'say-to-muavia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_oP7ThvbUx7jSlYJTjpiw89s6MLZQDzg',
    appId: '1:350364495319:ios:e609b7de71b925828aaf92',
    messagingSenderId: '350364495319',
    projectId: 'say-to-muavia',
    storageBucket: 'say-to-muavia.appspot.com',
    iosBundleId: 'com.example.sayAnythingToMuavia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_oP7ThvbUx7jSlYJTjpiw89s6MLZQDzg',
    appId: '1:350364495319:ios:e609b7de71b925828aaf92',
    messagingSenderId: '350364495319',
    projectId: 'say-to-muavia',
    storageBucket: 'say-to-muavia.appspot.com',
    iosBundleId: 'com.example.sayAnythingToMuavia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_PM0YNPFIZcFxG0LXyLSofyOib8gMrNs',
    appId: '1:350364495319:web:748cc4a84da881d98aaf92',
    messagingSenderId: '350364495319',
    projectId: 'say-to-muavia',
    authDomain: 'say-to-muavia.firebaseapp.com',
    storageBucket: 'say-to-muavia.appspot.com',
  );

}